[tool.poetry]
authors = ["Lunarmagpie <Bambolambo0@gmail.com>"]
description = "A docstring parser for Crescent."
license = "MPL-2.0"
name = "crescent-ext-docstrings"
packages = [
  {include = "crescent"},
]
version = "0.1.0"

[tool.poetry.dependencies]
"crescent.ext.docstrings" = {path = "crescent/ext/docstrings"}
hikari-crescent = "^0.2.0"
python = ">=3.8,<3.11"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
codespell = "^2.1.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.961"
nox = "^2022.1.7"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
